version: '3.8'

services:

  lending:
    build:
      context: ./django_apps
      dockerfile: Dockerfile
      target: lending
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - lending_static:/home/django/web/lending/static
      - lending_media:/home/django/web/lending/media
    env_file:
      - ./.env
    depends_on:
      - db
      - memcached

  manager:
    build:
      context: ./django_apps
      dockerfile: Dockerfile
      target: manager
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - manager_static:/home/django/web/manager/static
      - manager_media:/home/django/web/manager/media
    env_file:
      - ./.env
    depends_on:
      - db
      - memcached

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  memcached:
    image: memcached:1.6.21
    ports:
      - "11211:11211"

  nginx:
    build: ./nginx
    volumes:
      - lending_static:/home/django/web/lending/static
      - lending_media:/home/django/web/lending/media
      - manager_static:/home/django/web/manager/static
      - manager_media:/home/django/web/manager/media
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - lending
      - manager

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot/ --email rdc_atm@mail.ru --agree-tos --no-eff-email -d vibetorg.ru -d www.vibetorg.ru -d manager.vibetorg.ru
    depends_on:
      - nginx

  tg_bot:
    build: ./tg_bot
    env_file:
      - ./.env
    depends_on:
      - manager
    restart: always

volumes:
  postgres_data:
  lending_static:
  manager_static:
  lending_media:
  manager_media:
