# Generated by Django 5.0.4 on 2024-06-01 12:39

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('tg_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Телеграмм ID')),
                ('nickname', models.CharField(max_length=64, verbose_name='Никнейм')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Покупатель',
                'verbose_name_plural': 'Покупатели',
                'ordering': ('is_active',),
                'indexes': [models.Index(fields=['tg_id', 'is_active'], name='orders_buye_tg_id_1ff44a_idx'), models.Index(fields=['is_active'], name='orders_buye_is_acti_b9eaca_idx')],
            },
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('link', models.URLField(max_length=1000, verbose_name='Ссылка')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Цена товара')),
                ('status', models.CharField(choices=[('PE', 'В ожидании'), ('IP', 'Ждем ответ'), ('BA', 'На согласовании'), ('PA', 'Оплачено'), ('CO', 'Выполнен'), ('CA', 'Отменен')], default='PE', max_length=2, verbose_name='Статус')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.buyer', verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('getter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.buyer', verbose_name='Получатель')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.order', verbose_name='Заказ')),
            ],
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created'], name='orders_orde_created_51311f_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['buyer'], name='orders_orde_buyer_i_90aa29_idx'),
        ),
    ]
